[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "9G1yFcVSBFqwLeeQzcNZXm7DcBhaydUqFbH7j18JpxT1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ktruong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
