[features]
seeds = false
skip-lint = false
[programs.localnet]
mysolanaapp = "5rQiD9RrTKwypqSftFcBNYrfKueuqFs5kLEhEoiS6YS5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ktruong/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
